---
- hosts: webservers
  become: yes
  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /var/www/contact-us-bmc-car
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Copy build files to the deployment directory
      copy:
        src: ./build/
        dest: /var/www/contact-us-bmc-car
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
